---

services:
  git-proxy:
    #build: .
    image: chrisbensch/docker-gitcacher:latest
    container_name: git-cache-proxy
    ports:
      - "8080:80"
    volumes:
      - git-cache:/var/cache/nginx/git
      - ./logs:/var/log/nginx
    restart: unless-stopped
    environment:
      - TZ=UTC

volumes:
  git-cache:
    driver: local
